const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);let mediaItems=[],currentFilter="all",currentSearch="";
const publicUrl=p=>sb.storage.from(MEDIA_BUCKET).getPublicUrl(p).data.publicUrl; const esc=s=>(s||"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function status(e,t,err=false){if(e){e.textContent=t;e.classList.toggle('err',err)}}
async function loadMedia(){let r=await sb.from('media').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;mediaItems=r.data||[];render();if(window.renderAdmin)window.renderAdmin();if(window.updateStats)window.updateStats()}
function match(x,f,q){return(f==='all'||x.type===f)&&(!q||(x.name||'').toLowerCase().includes(q.toLowerCase()))}
function card(x,admin=false){let u=publicUrl(x.path),m=x.type==='video'?`<video src="${u}" controls preload="metadata"></video>`:`<img src="${u}" loading="lazy" alt="${esc(x.name)}">`;return `<article class="card">${m}<div class="meta"><span>${esc(x.name)}</span><small>${x.type}</small></div>${admin?`<div class="controls"><input class="rename" data-id="${x.id}" value="${esc(x.name)}"><button class="renameBtn" data-id="${x.id}">RENAME</button><button class="deleteBtn" data-id="${x.id}">DELETE</button></div>`:''}</article>`}
function render(){let e=document.getElementById('gallery');if(!e)return;let a=mediaItems.filter(x=>match(x,currentFilter,currentSearch));e.innerHTML=a.map(x=>card(x)).join('');document.getElementById('empty').hidden=!!a.length}
async function uploadFiles(files,el){let a=[...files],done=0;for(let f of a){if(!/^(image|video)\//.test(f.type)){status(el,`Skipped ${f.name}: unsupported`,true);continue}if(f.size>MAX_FILE_SIZE_MB*1048576){status(el,`Skipped ${f.name}: max ${MAX_FILE_SIZE_MB}MB`,true);continue}let p=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${(f.name.split('.').pop()||'bin').toLowerCase()}`;status(el,`Uploading ${done+1}/${a.length}: ${f.name}`);let u=await sb.storage.from(MEDIA_BUCKET).upload(p,f,{contentType:f.type,upsert:false});if(u.error){status(el,u.error.message,true);continue}let d=await sb.from('media').insert({name:f.name.replace(/\.[^/.]+$/,''),type:f.type.startsWith('video/')?'video':'image',mime:f.type,path:p,size_bytes:f.size});if(d.error){await sb.storage.from(MEDIA_BUCKET).remove([p]);status(el,d.error.message,true);continue}done++}status(el,`Done. ${done}/${a.length} uploaded.`);await loadMedia()}
document.addEventListener('DOMContentLoaded',async()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});document.getElementById('searchInput')?.addEventListener('input',e=>{currentSearch=e.target.value;render()});document.getElementById('publicUpload')?.addEventListener('change',e=>uploadFiles(e.target.files,document.getElementById('uploadStatus')));try{await loadMedia()}catch(e){status(document.getElementById('uploadStatus'),e.message,true)}});
